name: flutter_cafe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/фон.png
      - assets/images/cafe_layout.png
      - assets/images/cafecat.svg
      - assets/images/contact.png
      - assets/images/logo.png
      - assets/images/фон2.jpg
      - assets/images/фон3.jpg
      - assets/images/столы.png
      - assets/images/cat/
      - assets/images/menu/
      - assets/images/menu/1.jpg
      - assets/images/menu/2.jpg
      - assets/images/menu/3.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

